### ISSUE TITLE
Single bullet point folds in itself

### ISSUE THREAD

**Issue by mahaha** [lukaszkorecki/workflowish#5]
First off, thank you for making workflowish available, it is very helpful! 

Yet I've been encountering an issue, for which I hope there may be an easy solution. I will append my .vimrc, incase the issue lies there:

Whenever I write a bullet point which goes over my linebreak, it automatically continues on the following line. Yet when I fold a bullet point, every bullet point, which is longer than one line, folds as well. I've added two images to highlight what's happening. 

![vim1](https://f.cloud.github.com/assets/958607/1745749/3cf84252-6433-11e3-890c-2d34ac3e7bd8.jpg)
![vim2](https://f.cloud.github.com/assets/958607/1745751/40a4691c-6433-11e3-9b89-b42aaf1fedab.jpg)

Is there anyway to stop folding lines when they belong to one bullet point?

Thanks a lot!

``` .vimrc
set tw=100
set autoindent
set formatoptions=tcq
set com=fb:*
set formatlistpat=^\\s*[0-9*]\\+[\\]:.)}\\t\ ]\\s*
set spell
set spelllang=de
colorscheme synic
set fileencoding=utf8
execute pathogen#infect()
syntax on
filetype plugin indent on
``` 
**EDIT**

I've been able to stop the issue from repeating itself by adding the following lines to my .vimrc:

```
autocmd BufWinLeave *.* mkview
autocmd BufWinEnter *.* silent loadview
```

**Comment by hangtwenty** [comment]
@lukaszkorecki @mahaha should we just add the EDIT solution to readme? i.e.

---------

# Installation

Install with pathogen

## Configuration tweak recommended

This fixes an edge-case with folding bullets. We recommend you add this to your vimrc:

```
autocmd BufWinLeave *.* mkview
autocmd BufWinEnter *.* silent loadview
```

**Comment by lukaszkorecki** [comment]
@hangtwenty @mahaha @flugsio any reason why it can't be included in the workflowish code?

**Comment by hangtwenty** [comment]
@lukaszkorecki  Well, I don't have the command of Vim or Vimscript or (doing a ton of things to your vim that might interact with each other), to know whether that's a risky change or not. I'll defer to you or @mahaha  on what's best.

I don't mind making the code change when we know what is best

**Comment by lukaszkorecki** [comment]
@hangtwenty me neither :-), I think this shouldn't mess up too many things:

```viml
autocmd BufWinLeave *.wofl mkview
autocmd BufWinEnter *.wofl silent loadview
```


To address this without much risk it's best to update the README with that snippet and link to this issue.

**Comment by flugsio** [comment]
I don't like the workaround. If I understand the issue correctly, bullets spanning multiple lines should never be foldable? (maybe with a toggle)

Currently, there is no "multiline" bullets. Every line is a bullet/item regardless of what characters it begins with. They are foldable if they have lines under them with at least 1 full indent (2 spaces for example).

Another workaround is to use less indent for the next lines. This can be accomplished in multiple ways, for example using only 1 space, or prefix with some other character that is at the same indent.

```
* first
  * second bullet which continues
  \ on the next line
  _ starting with random character
   or less indent
   like this
  * third
    * third child
```

One solution is to not only check the indents, but also the characters to determine foldlevels. To add this feature in the code, it would need to scan the contents around every line and either compute relative to previous indentlevels or scan all the way to the root. For longer files this could cause a significant slowdown. Here is the relevant function https://github.com/lukaszkorecki/workflowish/blob/ca4f4e94ab0b4f5bf123fd376e1c6cd466596eb7/ftplugin/workflowish.vim#L172

**Comment by lukaszkorecki** [comment]
Ok, that sounds way too complicated fix for an edge case.

Lets add that snippet to the readme and link to this issue.

**Comment by hangtwenty** [comment]
@lukaszkorecki close it up?

**Comment by lukaszkorecki** [comment]
@hangtwenty done :+1:
