### ISSUE TITLE
ftdetect not being set for .wofl files

### ISSUE THREAD

**Issue by idvorkin** [lukaszkorecki/workflowish#6]
*Love the workflowish idea* 

I Installed workflowish via vundle on multiple machines, so I doubt this is machine specific.

When I open wofl files, the filetype is not set.  When I manually set the filetype, everything works perfectly. 

Is this expected? If not, how can I debug?

**Comment by lukaszkorecki** [comment]
Hi @idvorkin 

I'm not a vundle user (I like my setup simple git clone + pathogen), but we do have a ftdetect file https://github.com/lukaszkorecki/workflowish/blob/master/ftdetect/workflowish.vim so by vim standards everything should be working just fine.

As a workaround you can add 

```viml
autocmd BufNewFile,BufRead *.wofl set filetype=workflowish

```

to your `.vimrc` and everything will be working automagically

**Comment by idvorkin** [comment]
The workaround works, I'll update if I figure out what's wrong with vundle.

**Comment by lukaszkorecki** [comment]
Thanks @idvorkin

**Comment by flugsio** [comment]
It works in Vundle for me, it's probably because you need to turn of filetype before vundle config and then turn on again after. I encourage you to read all this https://github.com/VundleVim/Vundle.vim/blob/master/README.md

**Comment by idvorkin** [comment]
@flugsio That was the problem. Thank you for the tip, turns out my vundle config has been wrong for years :)
